// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH567P8P0zIamXONGznv0um3xZAMqLO9I',
    appId: '1:172262660003:web:77d6a361762686184fac16',
    messagingSenderId: '172262660003',
    projectId: 'projeto-game-phishing-190d4',
    authDomain: 'projeto-game-phishing-190d4.firebaseapp.com',
    storageBucket: 'projeto-game-phishing-190d4.appspot.com',
    measurementId: 'G-CQNFNH2Y6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZdgox114JsuPX8Oe6KFTtEBGrIaRPL0c',
    appId: '1:172262660003:android:e08ac8a40f8894204fac16',
    messagingSenderId: '172262660003',
    projectId: 'projeto-game-phishing-190d4',
    storageBucket: 'projeto-game-phishing-190d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt7CADPYv_ZkL0S0vHX-PWqd8EV21FXTY',
    appId: '1:172262660003:ios:cd02c3cd723a69a74fac16',
    messagingSenderId: '172262660003',
    projectId: 'projeto-game-phishing-190d4',
    storageBucket: 'projeto-game-phishing-190d4.appspot.com',
    iosClientId: '172262660003-d5jsrjgub004j6hcbk7rjqsle1p6ao3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.phishingGameProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt7CADPYv_ZkL0S0vHX-PWqd8EV21FXTY',
    appId: '1:172262660003:ios:cd02c3cd723a69a74fac16',
    messagingSenderId: '172262660003',
    projectId: 'projeto-game-phishing-190d4',
    storageBucket: 'projeto-game-phishing-190d4.appspot.com',
    iosClientId: '172262660003-d5jsrjgub004j6hcbk7rjqsle1p6ao3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.phishingGameProject',
  );
}
