// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwucIZ-RX6mBdgd7-psMPPh_zbxgOK-ZQ',
    appId: '1:77289202542:web:3dffedeb17ed4887c2577f',
    messagingSenderId: '77289202542',
    projectId: 'game-phishing-gpp',
    authDomain: 'game-phishing-gpp.firebaseapp.com',
    storageBucket: 'game-phishing-gpp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDV0Eagj4-sjl7OJSG3dtr6WdEZii1W4g',
    appId: '1:77289202542:android:ff8fdd35979662c6c2577f',
    messagingSenderId: '77289202542',
    projectId: 'game-phishing-gpp',
    storageBucket: 'game-phishing-gpp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxKEPmFiAyWDMPZCgHHKPZHTDu9G0W6Qk',
    appId: '1:77289202542:ios:13b929c8e7ed2572c2577f',
    messagingSenderId: '77289202542',
    projectId: 'game-phishing-gpp',
    storageBucket: 'game-phishing-gpp.appspot.com',
    iosClientId: '77289202542-26qtrjjl7me4klptdg934p3gpmgdm1lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.phishingGameProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxKEPmFiAyWDMPZCgHHKPZHTDu9G0W6Qk',
    appId: '1:77289202542:ios:13b929c8e7ed2572c2577f',
    messagingSenderId: '77289202542',
    projectId: 'game-phishing-gpp',
    storageBucket: 'game-phishing-gpp.appspot.com',
    iosClientId: '77289202542-26qtrjjl7me4klptdg934p3gpmgdm1lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.phishingGameProject',
  );
}
