// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrc2o8h4BJN3YgsKSYCR7wka1BWmcmc2c',
    appId: '1:444180175794:web:8b09e9e1c21c27bc9de2ab',
    messagingSenderId: '444180175794',
    projectId: 'phishing-game-project',
    authDomain: 'phishing-game-project.firebaseapp.com',
    storageBucket: 'phishing-game-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhLSY25u_hbxdGM-orgejWqRK_tXaJ7Lo',
    appId: '1:444180175794:android:3c007a7778fa67a39de2ab',
    messagingSenderId: '444180175794',
    projectId: 'phishing-game-project',
    storageBucket: 'phishing-game-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIDchrthPcwC5x3nNSXaF_Fpj91UeJeVc',
    appId: '1:444180175794:ios:627400d785f098669de2ab',
    messagingSenderId: '444180175794',
    projectId: 'phishing-game-project',
    storageBucket: 'phishing-game-project.appspot.com',
    iosClientId: '444180175794-fndpagafk2k7lius1q4hr3rfvo7bija0.apps.googleusercontent.com',
    iosBundleId: 'com.example.phishingGameProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIDchrthPcwC5x3nNSXaF_Fpj91UeJeVc',
    appId: '1:444180175794:ios:627400d785f098669de2ab',
    messagingSenderId: '444180175794',
    projectId: 'phishing-game-project',
    storageBucket: 'phishing-game-project.appspot.com',
    iosClientId: '444180175794-fndpagafk2k7lius1q4hr3rfvo7bija0.apps.googleusercontent.com',
    iosBundleId: 'com.example.phishingGameProject',
  );
}
